import type { CommandHandler } from '../../types';
import { ls } from './ls';
import { cd } from './cd';
import { pwd } from './pwd';
import { mkdir } from './mkdir';
import { touch } from './touch';
import { cat } from './cat';
import { cp } from './cp';
import { mv } from './mv';
import { rm } from './rm';
import { echo } from './echo';
import { grep } from './grep';
import { head } from './head';
import { tail } from './tail';
import { wc } from './wc';
import { sortCmd } from './sort';
import { uniq } from './uniq';
import { cut } from './cut';
import { chmod } from './chmod';
import { find } from './find';
import { which } from './which';
import { whoami } from './whoami';
import { chown } from './chown';
import { clear } from './clear';
import { historyCmd } from './historyCmd';
import { tee } from './tee';
import { less } from './less';
import { rmdir } from './rmdir';
import { more } from './more';
import { ln } from './ln';
import { cmp } from './cmp';
import { chgrp } from './chgrp';
import { login } from './login';
import { diff } from './diff';
import { date } from './date';
import { cal } from './cal';
import { shutdown } from './shutdown';
import { man } from './man';
import { exitCmd } from './exit';
import { tar } from './tar';
import { gzip, gunzip } from './gzip';
import { df } from './df';
import { du } from './du';
import { free } from './free';
import { ps } from './ps';
import { kill } from './kill';
import { top } from './top';
import { mount } from './mount';
import { umount } from './umount';
import { jobs } from './jobs';
import { bg } from './bg';
import { fg } from './fg';
import { nice } from './nice';
import { renice } from './renice';
import { env } from './env';
import { exportCmd } from './export';
import { set } from './set';
import { useradd } from './useradd';
import { userdel } from './userdel';
import { usermod } from './usermod';
import { groupadd } from './groupadd';
import { groupmod } from './groupmod';
import { at } from './at';
import { batch } from './batch';
import { cron } from './cron';
import { crontab } from './crontab';
import { vmstat } from './vmstat';
import { dd } from './dd';
import { mkswap } from './mkswap';
import { swapon } from './swapon';
import { quota } from './quota';
import { vi } from './vi';

export const commandRegistry: Record<string, CommandHandler> = {};

function register(cmd: CommandHandler) {
  commandRegistry[cmd.name] = cmd;
  if (cmd.aliases) {
    for (const alias of cmd.aliases) {
      commandRegistry[alias] = cmd;
    }
  }
}

register(ls);
register(cd);
register(pwd);
register(mkdir);
register(touch);
register(cat);
register(cp);
register(mv);
register(rm);
register(echo);
register(grep);
register(head);
register(tail);
register(wc);
register(sortCmd);
register(uniq);
register(cut);
register(chmod);
register(find);
register(which);
register(whoami);
register(chown);
register(clear);
register(historyCmd);
register(tee);
register(less);
register(rmdir);
register(more);
register(ln);
register(cmp);
register(chgrp);
register(login);
register(diff);
register(date);
register(cal);
register(shutdown);
register(man);
register(exitCmd);
register(tar);
register(gzip);
register(gunzip);
register(df);
register(du);
register(free);
register(ps);
register(kill);
register(top);
register(mount);
register(umount);
register(jobs);
register(bg);
register(fg);
register(nice);
register(renice);
register(env);
register(exportCmd);
register(set);
register(useradd);
register(userdel);
register(usermod);
register(groupadd);
register(groupmod);
register(at);
register(batch);
register(cron);
register(crontab);
register(vmstat);
register(dd);
register(mkswap);
register(swapon);
register(quota);
register(vi);
